[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_VNC_RESOLUTION)sx24
autorestart=true
user=sapuser

[program:fluxbox]
command=/usr/bin/fluxbox -display :1
autorestart=true
user=sapuser
environment=DISPLAY=:1

[program:x11vnc]
command=/usr/bin/x11vnc -forever -usepw -create -shared -rfbport 5900 -rfbauth /home/sapuser/.vnc/passwd -display :1
autorestart=true
user=sapuser

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autorestart=true
user=sapuser